# Generated by Django 4.2 on 2023-05-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_referencias_delete_teste_jobs_referencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('C', 'Em criação'), ('AA', 'Aguardando aprovação'), ('F', 'Finalizando')], default='C', max_length=2),
        ),
    ]
